stages:  
  - build

debian-package:  
  stage: build
  image: debian:bullseye
  script:
    - apt update
    - apt install -y dh-make dh-exec
    - dpkg-buildpackage -us -uc
    - mkdir build
    - mv ../agdsn-zsh-config*.deb build/

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

rpm-package:
  stage: build
  image: rockylinux
  script:
    - dnf install -y rpm-build
    - rpmbuild -bb rpm/agdsn-zsh-config.spec --define "_topdir $(pwd)/rpm/build" --define "_sourcedir $(pwd)"

  artifacts:
    paths:
      - rpm/build/RPMS/noarch/*
